[package]
name = "kundli_core"
version = "0.1.0"
edition = "2024"
authors = ["Mukesh Singh"]

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"

[lib]
crate-type = ["cdylib", "rlib"]
